server:
  port: 8080

spring:
  application:
    name: contratacao-service

  datasource:
    url: jdbc:postgresql://localhost:5432/contratacao
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

  jackson:
    serialization:
      INDENT_OUTPUT: true

app:
  sqs:
    nova-venda-url: http://localhost:4566/000000000000/nova-venda-criada

logging:
  level:
    root: INFO
    br.com.challenge: DEBUG
