spring:
  application:
    name: contratacao-service

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false

  jackson:
    serialization:
      INDENT_OUTPUT: true

app:
  sqs:
    nova-venda-url: http://localhost:4566/000000000000/nova-venda-criada
